name: Philanthropy
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.4=h50f4ffc_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py310hca03da5_1
  - pip=26.0.1=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.10.2=py310hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.46.3=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - contourpy==1.3.2
      - coverage==7.13.4
      - cycler==0.12.1
      - exceptiongroup==1.3.1
      - flake8==7.3.0
      - fonttools==4.61.1
      - iniconfig==2.3.0
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mccabe==0.7.0
      - numpy==2.2.6
      - pandas==2.3.3
      - philanthropy==0.1.0
      - pillow==12.1.1
      - pluggy==1.6.0
      - pycodestyle==2.14.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyparsing==3.3.2
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tomli==2.4.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
